title: Bruno Ruan
email: brunoruandecastro@gmail.com
description: As doses organizadas do que encontro entre o silêncio e o ruído da vida.
baseurl: ""
url: ""
twitter_username:
instagram_username: brunoruaan

theme: minima
plugins:
  - jekyll-feed