---
title: Bruno Ruan
email: brunoruandecastro@gmail.com
description: As dose organizadas do que encontro entre o silêncio e o ruído da vida.
baseurl: ""
url: ""
twitter_username:
instagram_username: brunoruaan

layout: default
theme: minima
plugins:
  - jekyll-feed
---